# Generated by Django 2.0.2 on 2018-03-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('updated_datetime', models.DateTimeField()),
                ('comment_text', models.TextField(blank=True, max_length=65535, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=65535, null=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('content', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=65535, null=True)),
                ('weight', models.FloatField()),
                ('is_balanced', models.BooleanField(default=False)),
                ('is_binary', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=65535, null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('intercept', models.FloatField(null=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.MlModel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.MlModel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='factor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Factor'),
        ),
    ]
