# Generated by Django 2.0.2 on 2018-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='content',
            field=models.FileField(blank=True, upload_to='datasets'),
        ),
    ]
