# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='org_name',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='intercept',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='intercept',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='modified',
            field=models.DateTimeField(blank=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factor',
            name='description',
            field=models.TextField(max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.TextField(max_length=65535, null=True),
        ),
    ]
