# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_mlmodel_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='non_categorical_columns',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
