# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_mlmodel_non_categorical_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='target_variable',
            field=models.TextField(max_length=65535, null=True),
        ),
    ]
