# Generated by Django 2.0.2 on 2018-04-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_mlmodel_target_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='model_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.MlModel'),
            preserve_default=False,
        ),
    ]
