# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_mlmodeldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='negative_threshold',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='positive_threshold',
            field=models.FloatField(null=True),
        ),
    ]
