# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20180406_0056'),
        ('restapi', '0008_comment_model_id'),
    ]

    operations = [
    ]
