# Generated by Django 2.0.2 on 2018-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20180406_0056'),
        ('restapi', '0008_comment_model_id'),
    ]

    operations = [
    ]
