# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_merge_20180407_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='factor_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='factor_name',
            field=models.CharField(default='Factor Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MlModel'),
        ),
    ]
