# Generated by Django 2.0.2 on 2018-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_merge_20180407_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='factor_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='factor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
