# Generated by Django 2.0.2 on 2018-04-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20180407_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MlModel'),
        ),
    ]
