# Generated by Django 2.0.2 on 2018-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20180407_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='target_var_alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='target_variable',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
